### ISSUE TITLE
[blots] additional AttributeError on erroneous badge input

### ISSUE THREAD

**Issue by Laogeodritt** [Worldbuilding/KazTron#129]
```
[2018-04-18 05:54:50,734] (DEBUG) kaztron.cog.blots.badges: Badge Manager: [2018-04-18 05:54:50 UTC] <#give-badges:Seán de Grá#5632> '**To:**@ZubZub [A Feast for Worms]\n**For:** <:Writing:389631794921865227> For giving me important advice, and reminding me that nothing needs to be perfect.' [in /kaztron-ib/KazTron/kaztron/cog/blots/badges.py:115]
[2018-04-18 05:54:50,742] (WARNING) kaztron.cog.blots.badges: Badge must mention exactly 1 user:  [in /kaztron-ib/KazTron/kaztron/cog/blots/badges.py:57]
[2018-04-18 05:54:50,835] (DEBUG) websockets.protocol: client << Frame(fin=True, opcode=1, data=b'{"t":"MESSAGE_CREATE","s":6765,"op":0,"d":{"type":0,"tts":false,"timestamp":"2018-04-18T05:54:50.736000+00:00","pinned":false,"nonce":null,"mentions":[],"mention_roles":[],"mention_everyone":false,"id":"436041902136098828","embeds":[],"edited_timestamp":null,"content":"**Error**: Badges must mention exactly 1 user.","channel_id":"400033644137152512","author":{"username":"Armarius","id":"416886818836054031","discriminator":"0471","bot":true,"avatar":"fc72107cf82203bf91d3c09d1c62090d"},"attachments":[],"guild_id":"283494372421533696"}}') [in /kaztron-ib/venv/lib/python3.5/site-packages/websockets/protocol.py:548]
[2018-04-18 05:54:50,836] (DEBUG) discord.client: Dispatching event socket_raw_receive [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/client.py:317]
[2018-04-18 05:54:50,837] (DEBUG) discord.gateway: WebSocket Event: {'s': 6765, 't': 'MESSAGE_CREATE', 'op': 0, 'd': {'mentions': [], 'channel_id': '400033644137152512', 'attachments': [], 'tts': False, 'edited_timestamp': None, 'author': {'id': '416886818836054031', 'username': 'Armarius', 'avatar': 'fc72107cf82203bf91d3c09d1c62090d', 'bot': True, 'discriminator': '0471'}, 'embeds': [], 'id': '436041902136098828', 'nonce': None, 'mention_everyone': False, 'content': '**Error**: Badges must mention exactly 1 user.', 'type': 0, 'timestamp': '2018-04-18T05:54:50.736000+00:00', 'guild_id': '283494372421533696', 'pinned': False, 'mention_roles': []}} [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/gateway.py:327]
[2018-04-18 05:54:50,838] (DEBUG) discord.client: Dispatching event socket_response [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/client.py:317]
[2018-04-18 05:54:50,839] (DEBUG) discord.client: Dispatching event message [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/client.py:317]
[2018-04-18 05:54:50,864] (DEBUG) discord.http: POST https://discordapp.com/api/v6/channels/400033644137152512/messages with {"content":"**Error**: Badges must mention exactly 1 user."} has returned 200 [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/http.py:138]
[2018-04-18 05:54:50,866] (DEBUG) discord.http: POST https://discordapp.com/api/v6/channels/400033644137152512/messages has received {'channel_id': '400033644137152512', 'mentions': [], 'attachments': [], 'tts': False, 'edited_timestamp': None, 'author': {'id': '416886818836054031', 'username': 'Armarius', 'avatar': 'fc72107cf82203bf91d3c09d1c62090d', 'bot': True, 'discriminator': '0471'}, 'embeds': [], 'id': '436041902136098828', 'nonce': None, 'mention_everyone': False, 'content': '**Error**: Badges must mention exactly 1 user.', 'type': 0, 'timestamp': '2018-04-18T05:54:50.736000+00:00', 'pinned': False, 'mention_roles': []} [in /kaztron-ib/venv/lib/python3.5/site-packages/discord/http.py:161]
[2018-04-18 05:54:50,867] (ERROR) kaztron.cog.core: Error occurred in message(<discord.message.Message object at 0x7f7870cbba40>, ) [in /kaztron-ib/KazTron/kaztron/cog/core.py:98]
Traceback (most recent call last):
  File "/kaztron-ib/venv/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/kaztron-ib/KazTron/kaztron/kazcog.py", line 184, in wrapper
    await func(*args, **kwargs)
  File "/kaztron-ib/KazTron/kaztron/cog/blots/badges.py", line 120, in on_message
    self.server.get_member(badge_row.user.discord_id),
AttributeError: 'NoneType' object has no attribute 'user'
```

**Comment by Laogeodritt** [comment]
Looks like it's a problem of not detecting when `self.add_badge` fails to add a badge
