### ISSUE TITLE
KazTron should handle situation that user does not allow PMs

### ISSUE THREAD

**Issue by Laogeodritt** [Worldbuilding/KazTron#35]
2018-02-23

```
[21:03] BOTBotTest9000: [ERROR] While executing [2018-02-24 02:03:58] <#bot_test:AntimatterNuke#7807> '.spotlight join'

Discord API error FORBIDDEN (status code: 403): Cannot send messages to this user

See log for details
```

**Comment by Laogeodritt** [comment]
@cxcfme Can you get me logs for this event, in the description? 2018-02-24 at 02:03 UTC

**Comment by cxcfme** [comment]
@Laogeodritt 

`[2018-02-24 02:03:59,280] (ERROR) kaztron.cog.core: While executing [2018-02-24 02:03:58] <#bot_test:AntimatterNuke#7807> '.spotlight join'

Discord API error FORBIDDEN (status code: 403): Cannot send messages to this user

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/kaztron/KazTron/kaztron/cog/spotlight.py", line 388, in join
    await self.bot.send_message(ctx.message.author, self.msg_join)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user
 [in /home/kaztron/KazTron/kaztron/cog/core.py:112]`

**Comment by Laogeodritt** [comment]
Deferred to v2.1 - PM limited users should be a limited case, this fix can be applied to the `role_man` feature that is absorbing spotlight join/part

**To evaluate:** Effect of this bug on usability, whether it is possible to simply improve the error message in the general case ("An error occurred" → "Can't send PM, make sure you (or the recipient) has PMs enabled")

Unsure if generic solution possible (also to catch the error in the case of help files, core's "don't know this command", etc.) - given that it only gives a discord.Forbidden error for the error handler
